
#twitter app Oauth info.
CONSUMER_KEY = "bMgoItrkScpW5z9f5l5ohJ4Al"
CONSUMER_SECRET = "V79yQVrkXi4Mpql5WOrK7D73IkgFXRz4lDMNbDdzZ2epO2NfDH"
ACCESS_TOKEN =  "993839802234454016-1Z40KKzIxohxgr2tyeaEuhWan6erzpk"
ACCESS_TOKEN_SECRET= "BXiEXVLJiahVozQ00haNmp3kx2A7js3PaH6qIrMstNfwn"

#settings for mongo db
MONGODB_SERVER = "127.0.0.1"
MONGODB_PORT = 27017
MONGODB_DB = "twitter_data"             # database name to save the crawled data
MONGODB_TWEET_COLLECTION = "tweets"     # collection name to save tweets

#authors to crawl
AUTHORS=[     
    "jihanwu",
    "VitalikButerin",
    "SatoshiLite",
    "brian_armstrong",
    "rogerkver",
    "aantonop",
    "NickSzabo4",
    "dtapscott",
    "gavinandresen",
    "laurashin",
    "thomaspower",
    "ErikVoorhees",
    "tylerwinklevoss",
    "barrysilbert",
    "TuurDemeester",
    "VinnyLingham",
    "CharlieShrem",
    "petertoddbtc",
    "adam3us",
    "ToneVays",
    "lopp",
    "TimDraper",
    "jgarzik",
    "bobbyclee",
    "fredwilson",
    "naval",
    "arrington",
    "jonmatonis",
    "StephanTual",
    "jimmysong",
    "cburniske",
    "DerinCag/",
    "FEhrsam",
    "VentureCoinist",
    "dinisguarda",
    "michaelkitces",
    "CarpeNoctom",
    "ethereumjoseph",
    "AriDavidPaul",
    "twobitidiot",
    "josephzhou",
    "brockpierce",
    "CremeDeLaCrypto",
    "novogratz",
    "dahongfei",
    "woonomic",
    "gavofyork",
    "niccary",
    "eric_lombrozo",
    "VladZamfir",
    "bgarlinghouse",
    "starkness",
    "iam_preethi",
    "kyletorpey",
    "IOHK_charles",
    "leashless",
    "com/Melt_Dem",
    "desantis",
    "slushcz",
    "bitcoinbyte",
    "SunnyStartups",
    "anondran",
    "alextapscott",
    "wmougayar",
    "proffaustus",
    "ryanxcharles",
    "Kris_HK",
    "ummjackson",
    "MrChrisEllis",
    "alansilbert",
    "dan_pantera",
    "muneeb",
    "nejc_kodric",
    "mbauwens",
    "francispouliot_",
    "OneMorePeter",
    "oleganza",
    "eiaine",
    "cryptomanran",
    "SusanneChishti",
    "_jonasschnelli_",
    "pierre_rochard",
    "ljxie",
    "juanbenet",
    "chrislarsensf",
    "spair",
    "iamjosephyoung",
    "prestonjbyrne",
    "bendavenport",
    "AriannaSimpson",
    "HeyTaiZen",
    "alexsunnarborg",
    "TonyGallippi",
    "AnselLindner",
    "dieguito",
    "certainassets",
    "joonian",
    "roasbeef",
    "oscarwgrut",
    "derose",
]
